/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class EditMenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditMenuAdmin.class.getName());

    /**
     * Creates new form EditMenuAdmin
     */
    public EditMenuAdmin() {
        initComponents();
        Gambar(Logo, "/View/logo besar.png");
        
    }

        private void Gambar(javax.swing.JLabel label, String resourcePath) {
        ImageIcon imgIco = new ImageIcon(
            getClass().getResource(resourcePath)
        );
        
        Image image = imgIco.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );

        label.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblIDMenu = new javax.swing.JLabel();
        lblNamaMenu = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtMenu = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        cbStok = new javax.swing.JComboBox<>();
        bttnSimpan = new javax.swing.JButton();
        TempatFoto = new javax.swing.JLabel();
        bttnGambar = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();
        cbKategori1 = new javax.swing.JComboBox<>();
        bbtnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 231, 221));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblIDMenu.setBackground(new java.awt.Color(255, 255, 255));
        lblIDMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        lblIDMenu.setForeground(new java.awt.Color(175, 139, 87));
        lblIDMenu.setText("ID MENU                   ");

        lblNamaMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        lblNamaMenu.setForeground(new java.awt.Color(175, 139, 87));
        lblNamaMenu.setText("NAMA MENU            ");

        lblHarga.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(175, 139, 87));
        lblHarga.setText("HARGA                        ");

        lblStok.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        lblStok.setForeground(new java.awt.Color(175, 139, 87));
        lblStok.setText("STOK                           ");

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setText("EDIT MENU");

        cbStok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERSEDIA", "KOSONG" }));

        bttnSimpan.setBackground(new java.awt.Color(200, 114, 114));
        bttnSimpan.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bttnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bttnSimpan.setText("SIMPAN PERUBAHAN");
        bttnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSimpanActionPerformed(evt);
            }
        });

        bttnGambar.setBackground(new java.awt.Color(174, 134, 77));
        bttnGambar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        bttnGambar.setForeground(new java.awt.Color(255, 255, 255));
        bttnGambar.setText("PILIH GAMBAR");
        bttnGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGambarActionPerformed(evt);
            }
        });

        lblKategori.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(175, 139, 87));
        lblKategori.setText("PILIHAN KATEGORI ");

        cbKategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KUE ULANG TAHUN", "ROTI", "BOLU", "KUE KERING" }));

        bbtnKembali.setBackground(new java.awt.Color(100, 149, 195));
        bbtnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bbtnKembali.setText("KEMBALI");
        bbtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaMenu)
                            .addComponent(lblIDMenu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(bttnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TempatFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKategori)
                        .addGap(18, 18, 18)
                        .addComponent(cbKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblStok)
                        .addGap(18, 18, 18)
                        .addComponent(cbStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bttnSimpan)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bbtnKembali)
                        .addGap(337, 337, 337))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDMenu)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamaMenu))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHarga)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStok)
                            .addComponent(cbStok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(lblKategori))
                    .addComponent(cbKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TempatFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bttnSimpan)
                .addGap(18, 18, 18)
                .addComponent(bbtnKembali)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser(new File(System.getProperty("user.home"), "Pictures"));
        jc.setDialogTitle("Pilih Gambar Produk");
        jc.setAcceptAllFileFilterUsed(false);
        jc.addChoosableFileFilter(
            new FileNameExtensionFilter("Gambar (JPG, JPEG, PNG)", "jpg", "jpeg", "png")
        );
        jc.setMultiSelectionEnabled(false);

        int res = jc.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File f = jc.getSelectedFile();

            // validasi ekstensi (double check)
            String n = f.getName().toLowerCase();
            if (!(n.endsWith(".jpg") || n.endsWith(".jpeg") || n.endsWith(".png"))) {
                JOptionPane.showMessageDialog(this, "Pilih file JPG/PNG.");
                return;
            }

            File fileGambarTerpilih = f;

            // preview ke label (pakai method kamu)
            TempatFoto(TempatFoto, fileGambarTerpilih);

            // opsional: aktifkan tombol tambah setelah ada gambar
            bttnSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_bttnGambarActionPerformed

    private void bttnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnSimpanActionPerformed

    private void bbtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnKembaliActionPerformed
        // TODO add your handling code here:
        MenuKueKeringAdmin mkka = new MenuKueKeringAdmin ();    
        mkka.setVisible(true);
    this.dispose();                                   
    }//GEN-LAST:event_bbtnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditMenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TempatFoto;
    private javax.swing.JButton bbtnKembali;
    private javax.swing.JButton bttnGambar;
    private javax.swing.JButton bttnSimpan;
    private javax.swing.JComboBox<String> cbKategori1;
    private javax.swing.JComboBox<String> cbStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIDMenu;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaMenu;
    private javax.swing.JLabel lblStok;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    private void TempatFoto(JLabel TempatFoto, File fileGambarTerpilih) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
