/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class EditMenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditMenuAdmin.class.getName());
    private File fileGambarTerpilih = null;

    /**
     * Creates new form EditMenuAdmin
     */
    public EditMenuAdmin() {
        initComponents();
        Gambar(Logo, "/View/logo besar.png");
        
    }

        private void Gambar(javax.swing.JLabel label, String resourcePath) {
        ImageIcon imgIco = new ImageIcon(
            getClass().getResource(resourcePath)
        );
        
        Image image = imgIco.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );

        label.setIcon(new ImageIcon(image));
    }
        private void TempatFoto(javax.swing.JLabel label, File file) {
    try {
        BufferedImage img = ImageIO.read(file);
        if (img == null) {
            JOptionPane.showMessageDialog(this, "File bukan gambar.");
            return;
        }

        int lw = label.getWidth();
        int lh = label.getHeight();
        double s = Math.min((double) lw / img.getWidth(), (double) lh / img.getHeight());
        int nw = Math.max(1, (int) Math.round(img.getWidth()  * s));
        int nh = Math.max(1, (int) Math.round(img.getHeight() * s));

        Image scaled = img.getScaledInstance(nw, nh, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(scaled));
        label.setText(null);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal baca gambar: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblIDMenu = new javax.swing.JLabel();
        lblNamaMenu = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtMenu = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        cbStok = new javax.swing.JComboBox<>();
        bttnSimpan = new javax.swing.JButton();
        bttnGambar = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();
        cbKategori1 = new javax.swing.JComboBox<>();
        bbtnKembali = new javax.swing.JButton();
        TempatFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 231, 221));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblIDMenu.setBackground(new java.awt.Color(255, 255, 255));
        lblIDMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblIDMenu.setForeground(new java.awt.Color(175, 139, 87));
        lblIDMenu.setText("ID Menu           : ");

        lblNamaMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNamaMenu.setForeground(new java.awt.Color(175, 139, 87));
        lblNamaMenu.setText("Nama Menu    :");

        lblHarga.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(175, 139, 87));
        lblHarga.setText("Harga                :");

        lblStok.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblStok.setForeground(new java.awt.Color(175, 139, 87));
        lblStok.setText("Stok                          :");

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setText("EDIT MENU");

        cbStok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERSEDIA", "KOSONG" }));

        bttnSimpan.setBackground(new java.awt.Color(197, 108, 111));
        bttnSimpan.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        bttnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bttnSimpan.setText("SIMPAN PERUBAHAN");
        bttnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSimpanActionPerformed(evt);
            }
        });

        bttnGambar.setBackground(new java.awt.Color(185, 154, 102));
        bttnGambar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        bttnGambar.setForeground(new java.awt.Color(255, 255, 255));
        bttnGambar.setText("Pilih Gambar");
        bttnGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGambarActionPerformed(evt);
            }
        });

        lblKategori.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(175, 139, 87));
        lblKategori.setText("Pilihan Kategori   :");

        cbKategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KUE ULANG TAHUN", "ROTI", "BOLU", "KUE KERING" }));

        bbtnKembali.setBackground(new java.awt.Color(79, 111, 128));
        bbtnKembali.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        bbtnKembali.setForeground(new java.awt.Color(255, 255, 255));
        bbtnKembali.setText("KEMBALI");
        bbtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(320, 320, 320))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(357, 357, 357))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblNamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIDMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(txtMenu))
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblStok)
                        .addGap(18, 18, 18)
                        .addComponent(cbStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bttnSimpan)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblKategori)
                                .addComponent(bttnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TempatFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(bbtnKembali)))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDMenu)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStok)
                    .addComponent(cbStok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaMenu)
                    .addComponent(lblKategori)
                    .addComponent(cbKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHarga)
                            .addComponent(bttnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(bttnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bbtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TempatFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser(new File(System.getProperty("user.home"), "Pictures"));
        jc.setDialogTitle("Pilih Gambar Produk");
        jc.setAcceptAllFileFilterUsed(false);
        jc.addChoosableFileFilter(
            new FileNameExtensionFilter("Gambar (JPG, JPEG, PNG)", "jpg", "jpeg", "png")
        );
        jc.setMultiSelectionEnabled(false);

        int res = jc.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File f = jc.getSelectedFile();

            // validasi ekstensi (double check)
            String n = f.getName().toLowerCase();
            if (!(n.endsWith(".jpg") || n.endsWith(".jpeg") || n.endsWith(".png"))) {
                JOptionPane.showMessageDialog(this, "Pilih file JPG/PNG.");
                return;
            }

            fileGambarTerpilih = f;

             //preview ke label (pakai method kamu)
            TempatFoto(TempatFoto, fileGambarTerpilih);

            // opsional: aktifkan tombol tambah setelah ada gambar
            bttnSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_bttnGambarActionPerformed

    private void bttnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnSimpanActionPerformed

    private void bbtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnKembaliActionPerformed
        // TODO add your handling code here:
        AdminDashboard ad = new AdminDashboard ();    
        ad.setVisible(true);
    this.dispose();                                   
    }//GEN-LAST:event_bbtnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditMenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TempatFoto;
    private javax.swing.JButton bbtnKembali;
    private javax.swing.JButton bttnGambar;
    private javax.swing.JButton bttnSimpan;
    private javax.swing.JComboBox<String> cbKategori1;
    private javax.swing.JComboBox<String> cbStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIDMenu;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaMenu;
    private javax.swing.JLabel lblStok;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

   }
