
package View;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Controller.ProductController;
import Model.Product;


/**
 *
 * @author LENOVO
 */
public class InputMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputMenu.class.getName());
    private File fileGambarTerpilih = null;
    /**
     * Creates new form InputMenu
     */
    Controller.ProductController controller = new Controller.ProductController();
    
    public InputMenu() {
        initComponents();
        GambarLogo(Logo, "/View/logo besar.png");  
        
        loadData();
    }
    
    private void loadData() {
        // 1. Judul Kolom
        String[] judul = {"ID", "Nama Roti", "Harga", "Stok", "Kategori"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(null, judul);
        
        // 2. Ambil data dari Controller
        // Pastikan 'controller' sudah dideklarasikan di bagian atas class
        java.util.List<Model.Product> listRoti = controller.ambilSemuaData();
        
        // 3. Masukkan ke Tabel
        for (Model.Product p : listRoti) {
            Object[] row = new Object[5];
            row[0] = p.getId();
            row[1] = p.getName();
            row[2] = p.getPrice();
            row[3] = p.getStock();
            row[4] = p.getCategory();
            model.addRow(row);
        }
        
        // 4. Set ke GUI
        tblRoti.setModel(model);
    }

        private void GambarLogo(javax.swing.JLabel label, String resourcePath) {
        ImageIcon imgIco = new ImageIcon(
            getClass().getResource(resourcePath)
        );
        
        Image image = imgIco.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );

        label.setIcon(new ImageIcon(image));
    }
        
        private void TempatFoto(javax.swing.JLabel label, File file) {
    try {
        BufferedImage img = ImageIO.read(file);
        if (img == null) {
            JOptionPane.showMessageDialog(this, "File bukan gambar.");
            return;
        }

        int lw = label.getWidth();
        int lh = label.getHeight();
        double s = Math.min((double) lw / img.getWidth(), (double) lh / img.getHeight());
        int nw = Math.max(1, (int) Math.round(img.getWidth()  * s));
        int nh = Math.max(1, (int) Math.round(img.getHeight() * s));

        Image scaled = img.getScaledInstance(nw, nh, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(scaled));
        label.setText(null);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal baca gambar: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblRoti = new javax.swing.JTable();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        TempatFoto = new javax.swing.JLabel();
        btnGambar = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(239, 231, 221));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 139, 87));
        jLabel2.setText("Input Nama Roti      :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 139, 87));
        jLabel3.setText("Input Harga               :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 139, 87));
        jLabel4.setText("Input Stok                  :");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(175, 139, 87));
        jLabel5.setText("Pilih Kategori        :");

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setText("INPUT MENU");

        tblRoti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRotiMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tblRoti);

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KUE ULANG TAHUN", "ROTI", "BOLU", "KUE KERING" }));

        btnTambah.setBackground(new java.awt.Color(150, 125, 183));
        btnTambah.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("+Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(183, 93, 93));
        btnEdit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(80, 147, 115));
        btnHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnGambar.setBackground(new java.awt.Color(185, 154, 102));
        btnGambar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnGambar.setForeground(new java.awt.Color(255, 255, 255));
        btnGambar.setText("Pilih Gambar");
        btnGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambarActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(79, 111, 128));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKeluar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(389, 389, 389)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(351, 351, 351)
                            .addComponent(btnTambah)
                            .addGap(29, 29, 29)
                            .addComponent(btnEdit)
                            .addGap(36, 36, 36)
                            .addComponent(btnHapus))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(btnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TempatFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnEdit)
                            .addComponent(btnHapus)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TempatFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser(new File(System.getProperty("user.home"), "Pictures"));
    jc.setAcceptAllFileFilterUsed(false);
    jc.addChoosableFileFilter(
        new FileNameExtensionFilter("Gambar (JPG, JPEG, PNG)", "jpg", "jpeg", "png")
    );
    jc.setMultiSelectionEnabled(false);

    int res = jc.showOpenDialog(this);
    if (res == JFileChooser.APPROVE_OPTION) {
        File f = jc.getSelectedFile();

        // validasi ekstensi (double check)
        String n = f.getName().toLowerCase();
        if (!(n.endsWith(".jpg") || n.endsWith(".jpeg") || n.endsWith(".png"))) {
            JOptionPane.showMessageDialog(this, "Pilih file JPG/PNG.");
            return;
        }

        fileGambarTerpilih = f;

        // preview ke label (pakai method kamu)
        TempatFoto(TempatFoto, fileGambarTerpilih);

        // opsional: aktifkan tombol tambah setelah ada gambar
        btnTambah.setEnabled(true);
    }
    }//GEN-LAST:event_btnGambarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil data dari kotak inputan
            String nama = txtNama.getText();
            // Konversi teks ke angka (Double/Integer)
            double harga = Double.parseDouble(txtHarga.getText());
            int stok = Integer.parseInt(txtStok.getText());
            String kategori = cbKategori.getSelectedItem().toString();

            // 2. Cek kalau inputan kosong (Opsional tapi bagus)
            if (nama.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nama roti tidak boleh kosong!");
                return;
            }

            // 3. Masukkan data ke "Wadah" (Model Product)
            // ID diisi 0 saja karena di database dia Auto Increment
            Model.Product rotiBaru = new Model.Product(0, nama, harga, stok, kategori);
            
            // 4. Panggil Controller untuk simpan ke Database
            controller.tambahData(rotiBaru);
            
            // 5. Refresh Tabel & Bersihkan Inputan
            loadData(); // <-- Panggil method sakti yang barusan kamu buat
            txtNama.setText("");
            txtHarga.setText("");
            txtStok.setText("");
            
            javax.swing.JOptionPane.showMessageDialog(this, "Mantap! Roti berhasil ditambahkan.");
            
        } catch (NumberFormatException e) {
            // Jaga-jaga kalau user ngisi Harga/Stok pakai huruf
            javax.swing.JOptionPane.showMessageDialog(this, "Harga dan Stok harus angka ya!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        // 1. Buka Jendela Dashboard Admin
        new View.AdminDashboard().setVisible(true);
        
        // 2. Tutup/Hancurkan Jendela InputMenu ini biar gak numpuk
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // 1. Cek apakah user sudah pilih baris di tabel?
        int baris = tblRoti.getSelectedRow();
        
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu roti yang mau dihapus!");
            return;
        }

        // 2. Munculkan Pop-up Konfirmasi (Biar gak salah pencet)
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Yakin mau menghapus roti ini?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        // 3. Kalau user pilih YES, baru dieksekusi
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Ambil ID dari kolom ke-0
                String idString = tblRoti.getValueAt(baris, 0).toString();
                int id = Integer.parseInt(idString);
                
                // Panggil Controller untuk hapus
                controller.hapusData(id);
                
                // Refresh Tabel & Bersihkan Form
                loadData();
                txtNama.setText("");
                txtHarga.setText("");
                txtStok.setText("");
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                
            } catch (Exception e) {
                System.out.println("Error Hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblRotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRotiMouseClicked
        int baris = tblRoti.getSelectedRow();
        
        if (baris != -1) {
            // Langsung ambil dari tabel dan masukkan ke Text Field
            txtNama.setText(tblRoti.getValueAt(baris, 1).toString());
            txtHarga.setText(tblRoti.getValueAt(baris, 2).toString());
            txtStok.setText(tblRoti.getValueAt(baris, 3).toString());
            
            cbKategori.setSelectedItem(tblRoti.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tblRotiMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        // 1. CEK: Apakah user sudah klik salah satu baris di tabel?
        int baris = tblRoti.getSelectedRow();
        
        if (baris == -1) {
            // Kalau belum pilih, marahin (kasih peringatan)
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu roti di tabel yang mau diedit!");
            return;
        }

        try {
            // 2. AMBIL ID DARI TABEL (KUNCI UTAMA)
            // Kita wajib tahu ID roti yang mau diedit. 
            // Asumsinya ID ada di kolom ke-0 (Paling kiri).
            String idString = tblRoti.getValueAt(baris, 0).toString();
            int id = Integer.parseInt(idString);
            
            // 3. AMBIL DATA BARU DARI KOTAK INPUT
            String nama = txtNama.getText();
            double harga = Double.parseDouble(txtHarga.getText());
            int stok = Integer.parseInt(txtStok.getText());
            String kategori = cbKategori.getSelectedItem().toString();

            // Validasi: Jangan biarkan nama kosong
            if (nama.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nama roti tidak boleh kosong!");
                return;
            }

            // 4. BUNGKUS DATA JADI OBJEK PRODUCT
            // (ID Lama + Data Baru)
            Model.Product rotiUpdate = new Model.Product(id, nama, harga, stok, kategori);
            
            // 5. SURUH CONTROLLER UPDATE KE DATABASE
            controller.editData(rotiUpdate);
            
            // 6. REFRESH TABEL (Biar perubahan langsung muncul)
            loadData(); 
            
            // 7. BERSIHKAN FORM
            txtNama.setText("");
            txtHarga.setText("");
            txtStok.setText("");
            
            // Kasih kabar sukses
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harga dan Stok harus angka!");
        } catch (Exception e) {
            System.out.println("Error Edit: " + e.getMessage());
            e.printStackTrace(); 
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InputMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TempatFoto;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGambar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblRoti;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
