/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Config.Koneksi;
import Controller.SessionUser;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Transaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Transaksi.class.getName());

    public static DefaultTableModel tableTransaksiModel = new DefaultTableModel();
    private static Transaksi instance;

    public Transaksi() {
        initComponents();
        Gambar(Logo, "/View/logo_besar.png");

        // set model tabel transaksi
        tableTransaksi.setModel(tableTransaksiModel);
        tableTransaksiModel.setColumnIdentifiers(
                new String[]{"ID", "Nama", "Jumlah", "Harga", "Total"}
        );

        // *** TAMPILKAN NAMA KASIR DARI SESSION (fullname) ***
        String namaKasir = SessionUser.getNamaUser(); // fullname yang diset waktu login
        if (namaKasir != null && !namaKasir.isEmpty()) {
            jTextField1.setText(namaKasir);
            jTextField1.setEditable(false);
        }

        // tanggal otomatis hari ini
        jDateChooser1.setDate(new Date());

        // tampilkan total awal
        hitungTotal();
    }
    
    public double hitungTotal() {
        double total = 0.0;
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            Object obj = model.getValueAt(i, 4); // kolom TOTAL
            if (obj == null) continue;

            double subtotal = Double.parseDouble(obj.toString());
            total += subtotal;
        }

        lblTotalBayar.setText(String.valueOf(total));
        return total;
    }

    private void Gambar(javax.swing.JLabel label, String resourcePath) {
        ImageIcon imgIco = new ImageIcon(
                getClass().getResource(resourcePath)
        );

        Image image = imgIco.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );

        label.setIcon(new ImageIcon(image));
    }

    public void addToCart(String id, String nama, int jumlah, double harga) {
        double total = jumlah * harga;

        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        model.addRow(new Object[]{
            id, nama, jumlah, harga, total
        });

        hitungTotal();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        bttnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnPilih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblTotalBayar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(239, 231, 221));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setText("Transaksi");

        bttnKembali.setBackground(new java.awt.Color(79, 111, 128));
        bttnKembali.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        bttnKembali.setForeground(new java.awt.Color(255, 255, 255));
        bttnKembali.setText("Keluar");
        bttnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnKembaliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 139, 87));
        jLabel2.setText("Nama Kasir                     :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 139, 87));
        jLabel3.setText("Tanggal                            :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 139, 87));
        jLabel4.setText("Uang User    :");

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTransaksi);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(175, 139, 87));
        jLabel5.setText("Metode Pembayaran   :");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRANSFER", "TUNAI" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(175, 139, 87));
        jLabel7.setText("Pilih Menu      :");

        jButton2.setBackground(new java.awt.Color(80, 147, 181));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cetak Struk");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(181, 85, 104));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(104, 147, 100));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnPilih.setText("Pilih");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(175, 139, 87));
        jLabel6.setText("Total Harga:");

        lblTotalBayar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblTotalBayar.setForeground(new java.awt.Color(175, 139, 87));
        lblTotalBayar.setText("blum ada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPilih)
                                .addGap(125, 125, 125))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnKembali))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnPilih))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:


    int row = tableTransaksi.getSelectedRow();

    if(row == -1){
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih item dulu!");
        return;
    }

    DefaultTableModel model = tableTransaksiModel;
    model.removeRow(row);

    hitungTotal();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int row = tableTransaksi.getSelectedRow();

    if(row == -1){
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih item dulu!");
        return;
    }

    String input = javax.swing.JOptionPane.showInputDialog(this, "Masukkan jumlah baru:");

    if(input == null || input.trim().equals("")) return;

    int jumlah = Integer.parseInt(input);

    if(jumlah < 1){
        javax.swing.JOptionPane.showMessageDialog(this, "Jumlah minimal 1!");
        return;
    }

    double harga = Double.parseDouble(tableTransaksiModel.getValueAt(row, 3).toString());

    tableTransaksiModel.setValueAt(jumlah, row, 2);
    tableTransaksiModel.setValueAt(jumlah * harga, row, 4);

    hitungTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bttnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnKembaliActionPerformed
        // TODO add your handling code here:
        Logout.kembaliKeLogin(this);
    }//GEN-LAST:event_bttnKembaliActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
        try {
            PilihMenu pl = new PilihMenu();
            pl.setLocationRelativeTo(this); // optional: biar muncul di tengah
            pl.setVisible(true);
            this.setVisible(false);         // atau this.dispose();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal membuka PilihMenu", ex);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal membuka menu.\nCek koneksi database / MakananController.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // 1. Validasi keranjang
        // 1. Validasi keranjang
        if (tableTransaksiModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Keranjang masih kosong.");
            return;
        }

        String kasir = jTextField1.getText().trim(); // ini cuma untuk tampilan / struk
        if (kasir.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama kasir belum diisi.");
            return;
        }

        Date tanggal = jDateChooser1.getDate();
        if (tanggal == null) {
            tanggal = new Date();
        }

        String metode = (String) jComboBox1.getSelectedItem();
        double total = hitungTotal();

        String uangUserStr = jTextField3.getText().trim();
        double uangUser = 0;
        if (!uangUserStr.isEmpty()) {
            try {
                uangUser = Double.parseDouble(uangUserStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Format uang user tidak valid.");
                return;
            }
            if (uangUser < total) {
                JOptionPane.showMessageDialog(this, "Uang user kurang dari total.");
                return;
            }
        }

        Connection conn = null;

        try {
            conn = Koneksi.configDB();
            conn.setAutoCommit(false);

            // 2. Ambil user_id langsung dari SessionUser (TIDAK QUERY LAGI KE users)
            int userId = SessionUser.getUserId();
            if (userId <= 0) {
                throw new SQLException("User ID di SessionUser tidak valid. Silakan login ulang.");
            }

            // 3. Insert ke tabel transactions
            int idTransaksiBaru;
            String sqlTrx = "INSERT INTO transactions (user_id, transaction_date, total_amount) VALUES (?, ?, ?)";
            try (PreparedStatement psTrx = conn.prepareStatement(sqlTrx, Statement.RETURN_GENERATED_KEYS)) {
                psTrx.setInt(1, userId);
                psTrx.setTimestamp(2, new Timestamp(tanggal.getTime()));
                psTrx.setDouble(3, total);
                psTrx.executeUpdate();

                try (java.sql.ResultSet rsKey = psTrx.getGeneratedKeys()) {
                    if (rsKey.next()) {
                        idTransaksiBaru = rsKey.getInt(1);
                    } else {
                        throw new SQLException("Gagal mendapatkan ID transaksi baru.");
                    }
                }
            }

            // 4. Insert ke tabel transaction_details
            String sqlDet = "INSERT INTO transaction_details (transaction_id, product_id, quantity, subtotal) " +
                            "VALUES (?, ?, ?, ?)";
            try (PreparedStatement psDet = conn.prepareStatement(sqlDet)) {
                for (int i = 0; i < tableTransaksiModel.getRowCount(); i++) {
                    int productId = Integer.parseInt(tableTransaksiModel.getValueAt(i, 0).toString());
                    int qty       = Integer.parseInt(tableTransaksiModel.getValueAt(i, 2).toString());
                    double sub    = Double.parseDouble(tableTransaksiModel.getValueAt(i, 4).toString());

                    psDet.setInt(1, idTransaksiBaru);
                    psDet.setInt(2, productId);
                    psDet.setInt(3, qty);
                    psDet.setDouble(4, sub);
                    psDet.addBatch();
                }
                psDet.executeBatch();
            }

            conn.commit();

            // 5. Buat PDF struk dengan iText
            buatPdfStruk(idTransaksiBaru, kasir, tanggal, metode, total, uangUser);

            JOptionPane.showMessageDialog(this,
                    "Transaksi berhasil disimpan dan struk PDF dibuat.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);

            // 6. Bersihkan form
            tableTransaksiModel.setRowCount(0);
            hitungTotal();
            jTextField3.setText("");

        } catch (Exception ex) {
            if (conn != null) {
                try { conn.rollback(); } catch (SQLException e1) { /* ignore */ }
            }
            logger.log(java.util.logging.Level.SEVERE, "Gagal menyimpan transaksi / membuat struk", ex);
            JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan transaksi / membuat struk:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try {
                    conn.setAutoCommit(true);
                    conn.close();
                } catch (SQLException e1) { /* ignore */ }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buatPdfStruk(int idTransaksi, String kasir, Date tanggal,
        String metode, double total, double uangUser) throws Exception {

        // 3. Siapkan file PDF tujuan
        SimpleDateFormat sdfFile = new SimpleDateFormat("yyyyMMdd_HHmmss");
        String timeStamp = sdfFile.format(new Date());

        File folder = new File(System.getProperty("user.home"), "Struk_TokoRoti");
        if (!folder.exists()) {
            folder.mkdirs();
        }

        File pdfFile = new File(folder, "struk_" + timeStamp + ".pdf");

        // 4. Buat PDF dengan iText
        SimpleDateFormat sdfTgl = new SimpleDateFormat("dd-MM-yyyy HH:mm");

        Document doc = new Document();
        PdfWriter.getInstance(doc, new FileOutputStream(pdfFile));

        doc.open();
        doc.add(new Paragraph("Toko Roti SANDX"));
        doc.add(new Paragraph("ID Transaksi : " + idTransaksi));
        doc.add(new Paragraph("Kasir        : " + kasir));
        doc.add(new Paragraph("Tanggal      : " + sdfTgl.format(tanggal)));
        doc.add(new Paragraph("Metode Bayar : " + (metode == null ? "-" : metode)));
        doc.add(new Paragraph(" "));

        PdfPTable pdfTable = new PdfPTable(5);
        pdfTable.setWidthPercentage(100);
        pdfTable.addCell("No");
        pdfTable.addCell("Nama");
        pdfTable.addCell("Qty");
        pdfTable.addCell("Harga");
        pdfTable.addCell("Total");

        for (int i = 0; i < tableTransaksiModel.getRowCount(); i++) {
            pdfTable.addCell(String.valueOf(i + 1));
            pdfTable.addCell(String.valueOf(tableTransaksiModel.getValueAt(i, 1)));
            pdfTable.addCell(String.valueOf(tableTransaksiModel.getValueAt(i, 2)));
            pdfTable.addCell(String.valueOf(tableTransaksiModel.getValueAt(i, 3)));
            pdfTable.addCell(String.valueOf(tableTransaksiModel.getValueAt(i, 4)));
        }

        doc.add(pdfTable);
        doc.add(new Paragraph(" "));
        doc.add(new Paragraph("TOTAL   : " + total));
        if (uangUser > 0) {
            doc.add(new Paragraph("BAYAR   : " + uangUser));
            doc.add(new Paragraph("KEMBALI : " + (uangUser - total)));
        }

        doc.close();

        JOptionPane.showMessageDialog(this,
                "Struk tersimpan di:\n" + pdfFile.getAbsolutePath(),
                "Struk PDF",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Transaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton bttnKembali;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblTotalBayar;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
